owner: vaishnavvijay-prog
repo: astridex-status

sites:
  - name: Website
    url: https://astridex.com
  - name: API
    url: https://astridex.com/api/access

status-website:
  baseUrl: /astridex-status
  name: Astridex
